// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 711 06/05/2020)
// Created on Sat Feb 03 22:56:54 2024

SE13_Relogio_Aula_Sch SE13_Relogio_Aula_Sch_inst
(
	.rst(rst_sig) ,	// input  rst_sig
	.clk(clk_sig) ,	// input  clk_sig
	.ajuste(ajuste_sig) ,	// input  ajuste_sig
	.dh(dh_sig) ,	// output [7:0] dh_sig
	.uh(uh_sig) ,	// output [7:0] uh_sig
	.dm(dm_sig) ,	// output [7:0] dm_sig
	.um(um_sig) ,	// output [7:0] um_sig
	.ds(ds_sig) ,	// output [7:0] ds_sig
	.us(us_sig) 	// output [7:0] us_sig
);

